name = "mbti-love-diagnosis"

# nodejs_compat v2 を使うために 2024-09-23 以降にしておく
compatibility_date = "2024-09-23"

# ここがポイント
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages で Next.js を動かすときによく使う設定
pages_build_output_dir = ".vercel/output/static"
